# Generated by Django 4.2.4 on 2024-02-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='transportista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.transportista'),
            preserve_default=False,
        ),
    ]
