# Generated by Django 4.2.4 on 2024-02-19 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_paquete_cliente_paquete_transportista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='estado_entrega',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='transportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.transportista'),
        ),
    ]
